<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome!</title>
    <link rel="stylesheet" href="/assets/welcome.css">
</head>
<body>
    <div id="app">
        <div id="content">
            <div id="head">
                <h1>Pluton<sup>php</sup></h1>
            </div>
            <div id="body">
                <span>MVC Framework by <a href="https://github.com/sabuhiali">Sabuhi Ali</a></span>
            </div>
        </div>
    </div>
</body>
</html>